name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean verify
        env:
          CI: true

      - name: Upload Test Results (artifact)
        if: always() # Always run this step even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results/test/ # Path to JUnit XML files

      - name: Publish Test Results (GitHub Actions annotations)
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            build/test-results/**/*.xml
            build/test-results/**/*.trx
            build/test-results/**/*.json
